

- name: ufw-firewall configuration
  hosts: "*"
  become: yes
  tasks:
    - name: install ufw
      apt:
        name: ufw
        state: present
        update_cache: true

    - name: allow ssh
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: deny incoming
      community.general.ufw:
        rule: deny
        direction: in
        state: enabled

    - name: allow outgoing
      community.general.ufw:
        rule: allow
        direction: out
        state: enabled
      
    - name: check whether ufw status is active
      shell: ufw status
      changed_when: false
      register: ufw_check

    - debug:
        msg: "{{ ufw_check }}"

    

      